version: "3.9"

services:
  node:
    image: asmh1989/ubuntu-slurm
    hostname: gpu27
    container_name: node_gpu_27
    restart: always
    #pid: host
    shm_size: '4gb'
    ulimits:
      memlock: -1
    user: admin
    privileged: true
    volumes:
      - /public:/public
      - ./docker-entrypoint.sh:/etc/slurm/docker-entrypoint.sh
      - /mnt:/mnt
      - /etc/localtime:/etc/localtime:ro
      - /public/slurm/hosts.allow:/etc/hosts.allow
      - /public/slurm/hosts.deny:/etc/hosts.deny
    environment:
      - SLURM_NODENAME=gpu27
    ports:
      - 6818:6818
      - 6817:6817
      - "6666:22"
    extra_hosts:
      - "szdata:192.168.2.26"
    # links:
    #   - slurmmaster
    deploy:
      resources:
        # limits:
        #   cpus: "32.0"
        #   memory: 48G
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0", "1", "2", "3" ]
              capabilities: [ gpu ]
